language: python
# Use Python for Vint.
python:
  - '3.6'
notifications:
  email: false

# Cache compiled Vim.
cache:
  directories:
    - '$HOME/vim'

# Run against vim 8.0.0400, can add multiple entries to test against multiple
# Vims.
matrix:
  include:
    - env: 'VIM_VERSION=v8.0.0400'
    #- env: 'VIM_VERSION=v8.0.1400'

install: |
  (
    set -euC

    # Move plugin to more logical location.
    cd ~
    mkdir -p ~/.vim/pack/plugin/start
    mv "$TRAVIS_BUILD_DIR" ~/.vim/pack/plugin/start

    # Install Vim if there it doesn't exist yet.
    if [ ! -e "$HOME/vim/bin/vim" ]; then
      git clone -q --depth 1 --branch "$VIM_VERSION" https://github.com/vim/vim $HOME/vim-src
      ( cd $HOME/vim-src && ./configure --prefix $HOME/vim --with-features=huge --disable-gui )
      ( cd $HOME/vim-src && make install )
    fi

    # Install vint.
    pip3 install -q vim-vint covimerage codecov

    # Clone testing.vim
    git clone -q --depth 1 https://github.com/arp242/testing.vim.git ~/testing.vim
  )

script: |
  (
    set -euC

    cd "$HOME/.vim/pack/plugin/start/$(basename "$TRAVIS_BUILD_DIR")"
    export TEST_VIM="$HOME/vim/bin/vim"
    $HOME/testing.vim/tvim test -p coverage.xml ./...
    $HOME/testing.vim/tvim lint ./...
  )

after_success: |
  (
    set -euC

    cd "$HOME/.vim/pack/plugin/start/$(basename "$TRAVIS_BUILD_DIR")"
    codecov -X search gcov pycov -f coverage.xml --required
  )
